// lib/tarot.js — 22 Arcanos Maiores + sorteio com chance de inversão

export const ARCANOS_MAIORES = [
  {
    id: 0,
    nome: 'O Louco',
    simbolo: '🌟',
    palavrasChave: ['Início', 'Liberdade', 'Salto de fé'],
    significado: 'Um novo ciclo começa. Convite para agir sem garantias, confiar no movimento e deixar o controle de lado.',
    significadoInvertido: 'Impulsividade sem direção. O medo de errar paralisa o primeiro passo.',
  },
  {
    id: 1,
    nome: 'O Mago',
    simbolo: '✦',
    palavrasChave: ['Manifestação', 'Vontade', 'Ação criativa'],
    significado: 'Você tem as ferramentas. O momento pede uso consciente do que já existe em você — não espera.',
    significadoInvertido: 'Potencial disperso. Energia sem foco ou uso manipulado do poder pessoal.',
  },
  {
    id: 2,
    nome: 'A Sacerdotisa',
    simbolo: '🌙',
    palavrasChave: ['Intuição', 'Mistério', 'Saber interno'],
    significado: 'A resposta já está em você. Momento de silêncio, escuta interna e confiança no que não é visível.',
    significadoInvertido: 'Desconexão da própria voz. Decisões guiadas por barulho externo em vez de percepção real.',
  },
  {
    id: 3,
    nome: 'A Imperatriz',
    simbolo: '🌿',
    palavrasChave: ['Abundância', 'Criação', 'Cuidado'],
    significado: 'Ciclo de fertilidade e crescimento. O que você nutre agora vai florescer. Cuidar sem perder de vista a própria necessidade.',
    significadoInvertido: 'Autocuidado negligenciado. Dar demais e receber de menos cria esgotamento invisível.',
  },
  {
    id: 4,
    nome: 'O Imperador',
    simbolo: '⚔️',
    palavrasChave: ['Estrutura', 'Autoridade', 'Disciplina'],
    significado: 'Construção com método. Liderar a própria vida com clareza e estabelecer limites que protegem o que importa.',
    significadoInvertido: 'Rigidez ou abdicação de poder. Controle excessivo ou incapacidade de assumir responsabilidade.',
  },
  {
    id: 5,
    nome: 'O Hierofante',
    simbolo: '🏛️',
    palavrasChave: ['Tradição', 'Orientação', 'Pertencimento'],
    significado: 'Buscar sabedoria em quem já caminhou. Respeitar o que foi construído sem perder a própria perspectiva.',
    significadoInvertido: 'Conformismo sufocante ou rebeldia sem direção. Romper regras sem saber o que construir no lugar.',
  },
  {
    id: 6,
    nome: 'Os Amantes',
    simbolo: '💞',
    palavrasChave: ['Escolha', 'União', 'Valores'],
    significado: 'Um momento de decisão alinhada com o que você realmente valoriza — não com o que parece mais seguro.',
    significadoInvertido: 'Desalinhamento interno. Escolhas feitas por medo ou para agradar levam a caminhos errados.',
  },
  {
    id: 7,
    nome: 'O Carro',
    simbolo: '🏹',
    palavrasChave: ['Conquista', 'Direção', 'Determinação'],
    significado: 'Avançar com foco. Você tem o que é preciso para vencer — mas exige dominar impulsos contrários.',
    significadoInvertido: 'Dispersão de energia. Forças internas conflitantes travam o movimento mesmo quando o caminho está claro.',
  },
  {
    id: 8,
    nome: 'A Força',
    simbolo: '🦁',
    palavrasChave: ['Coragem', 'Paciência', 'Domínio suave'],
    significado: 'O verdadeiro poder não grita. Agir com presença e gentileza é mais efetivo que força bruta.',
    significadoInvertido: 'Dúvida sobre a própria capacidade. Ou uso de força onde sutileza resolveria.',
  },
  {
    id: 9,
    nome: 'O Eremita',
    simbolo: '🕯️',
    palavrasChave: ['Solidão', 'Busca interior', 'Sabedoria'],
    significado: 'Recuar para dentro. Não é isolamento — é o silêncio necessário para ouvir o que importa antes de agir.',
    significadoInvertido: 'Isolamento como fuga. Evitar conexão por medo de ser visto ou julgado.',
  },
  {
    id: 10,
    nome: 'A Roda da Fortuna',
    simbolo: '☯️',
    palavrasChave: ['Ciclo', 'Mudança', 'Destino'],
    significado: 'Tudo muda. Um ciclo se fecha e outro começa. Soltar o que passou é o que permite o novo entrar.',
    significadoInvertido: 'Resistência à mudança. Apego ao que já não serve cria estagnação.',
  },
  {
    id: 11,
    nome: 'A Justiça',
    simbolo: '⚖️',
    palavrasChave: ['Equilíbrio', 'Verdade', 'Consequência'],
    significado: 'O que você semeou chega. Momento de honestidade total — com as escolhas feitas e as que ainda precisam ser feitas.',
    significadoInvertido: 'Desonestidade consigo mesmo. Evitar responsabilidade pelas próprias decisões.',
  },
  {
    id: 12,
    nome: 'O Enforcado',
    simbolo: '🌊',
    palavrasChave: ['Pausa', 'Entrega', 'Nova perspectiva'],
    significado: 'Parar voluntariamente muda o ângulo. O que parecia bloqueio pode ser o momento certo de soltar o controle.',
    significadoInvertido: 'Resistência à pausa. Forçar movimento quando o ciclo pede espera cria mais enredo.',
  },
  {
    id: 13,
    nome: 'A Morte',
    simbolo: '🌑',
    palavrasChave: ['Transformação', 'Fim de ciclo', 'Renascimento'],
    significado: 'Não é fim — é transformação. O que precisa morrer para que algo novo possa nascer está pedindo passagem.',
    significadoInvertido: 'Agarrar-se ao que já acabou. Medo de transformação que atrasa o inevitável.',
  },
  {
    id: 14,
    nome: 'A Temperança',
    simbolo: '✨',
    palavrasChave: ['Equilíbrio', 'Integração', 'Fluxo'],
    significado: 'Misturar opostos com sabedoria. O excesso em qualquer direção cria desequilíbrio — o meio é o caminho.',
    significadoInvertido: 'Extremos sem moderação. Excesso ou carência em alguma área da vida pedindo atenção.',
  },
  {
    id: 15,
    nome: 'O Diabo',
    simbolo: '🔗',
    palavrasChave: ['Sombra', 'Apego', 'Ilusão de prisão'],
    significado: 'O que te prende, você criou. A corrente existe — mas não é tão pesada quanto parece. Liberdade começa em nomear o padrão.',
    significadoInvertido: 'Libertação que ainda não foi completada. Ver a corrente mas ainda não ter coragem de soltar.',
  },
  {
    id: 16,
    nome: 'A Torre',
    simbolo: '⚡',
    palavrasChave: ['Ruptura', 'Revelação', 'Queda do falso'],
    significado: 'O que foi construído sobre base falsa vai cair. A ruptura dói mas limpa o terreno para algo real.',
    significadoInvertido: 'Resistência à queda inevitável. Sustentar o que já não funciona por medo do vazio.',
  },
  {
    id: 17,
    nome: 'A Estrela',
    simbolo: '⭐',
    palavrasChave: ['Esperança', 'Renovação', 'Fé'],
    significado: 'Depois da tempestade, algo se restaura. Permita-se receber o que o momento está oferecendo sem pressa.',
    significadoInvertido: 'Descrença que bloqueia a recepção. Dificuldade de confiar que o ciclo bom pode acontecer.',
  },
  {
    id: 18,
    nome: 'A Lua',
    simbolo: '🌕',
    palavrasChave: ['Ilusão', 'Inconsciente', 'Medo'],
    significado: 'O que está nas sombras influencia tudo. Momento de olhar para o que você não quer ver — está ditando o resultado.',
    significadoInvertido: 'Confusão que se clarifica. Os medos perdem força quando expostos à consciência.',
  },
  {
    id: 19,
    nome: 'O Sol',
    simbolo: '☀️',
    palavrasChave: ['Clareza', 'Vitalidade', 'Alegria'],
    significado: 'Clareza e energia. O que estava obscuro se ilumina. Momento de expressar e agir com autenticidade.',
    significadoInvertido: 'Brilho bloqueado. Dificuldade em se expressar ou receber reconhecimento por insegurança.',
  },
  {
    id: 20,
    nome: 'O Julgamento',
    simbolo: '🔔',
    palavrasChave: ['Chamado', 'Reavaliação', 'Recomeço consciente'],
    significado: 'Um chamado para revisão profunda. O passado foi vivido — agora é hora de integrar e responder ao que a vida pede.',
    significadoInvertido: 'Autocrítica paralisante. Julgamento de si mesmo que impede o movimento necessário.',
  },
  {
    id: 21,
    nome: 'O Mundo',
    simbolo: '🌍',
    palavrasChave: ['Completude', 'Realização', 'Integração'],
    significado: 'Um ciclo se completa com inteireza. Reconhecer o que foi construído e estar pronta para o próximo nível.',
    significadoInvertido: 'Ciclo incompleto. Sensação de estar quase lá mas algo ainda não foi integrado.',
  },
];

/**
 * Sorteia um arcano maior aleatoriamente.
 * 30% de chance de vir invertida.
 * @returns {{ id: number, nome: string, simbolo: string, palavrasChave: string[],
 *             significado: string, significadoInvertido: string, invertida: boolean }}
 */
export function sortearCarta() {
  const carta = ARCANOS_MAIORES[Math.floor(Math.random() * ARCANOS_MAIORES.length)];
  const invertida = Math.random() < 0.3;
  return { ...carta, invertida };
}

// Prompts em inglês para geração de imagem via Pollinations.ai
// NÃO incluir texto/nomes — o overlay é feito via HTML/CSS
export const TAROT_PROMPTS_EN = {
  'O Louco':           'joyful wanderer at cliff edge with small white dog, sun rising over mountain peaks, boundless horizon, carefree spirit, colorful knapsack',
  'O Mago':            'robed magician with wand raised toward sky, altar with chalice sword wand and pentacle, cosmic energy beams, infinity symbol above head',
  'A Sacerdotisa':     'veiled priestess seated between two marble pillars, crescent moon crown, scroll on lap, mysterious veil, sacred feminine power',
  'A Imperatriz':      'crowned empress on lush throne in forest, flowing golden robes, wheat field, pomegranates, Venus shield, divine feminine abundance',
  'O Imperador':       'armored emperor on carved stone throne, mountain peaks behind, golden ankh scepter, geometric patterns, sovereign authority',
  'O Hierofante':      'robed high priest on ornate sacred throne, two acolytes kneeling, triple crown, two crossed keys, sacred ceremony pillars',
  'Os Amantes':        'two figures beneath radiant archangel blessing, garden of eden, tree of knowledge, blazing sun above, divine union and choice',
  'O Carro':           'armored warrior on chariot pulled by black and white sphinxes, walled city, star canopy, victory and willpower',
  'A Força':           'graceful woman gently closing lion mouth with flowers, golden infinity symbol above head, lemniscate, gentle strength',
  'O Eremita':         'cloaked wise elder on snowy mountain peak holding lantern with six-pointed star, wooden staff, stars above, solitary wisdom',
  'A Roda da Fortuna': 'cosmic wheel with mystical symbols sphinx on top serpent descending, four winged creatures in corners, fate cycles universe',
  'A Justiça':         'robed figure holding balanced scales and upright sword, two stone pillars, red veil behind, cardinal virtue truth',
  'O Enforcado':       'serene figure hanging upside down from tau cross by one ankle, golden halo of light, hands behind back, surrender and new perspective',
  'A Morte':           'skeletal figure in black armor riding white horse, white rose banner, fallen king at feet, sun rising between towers',
  'A Temperança':      'winged angel pouring liquid between golden cups, one foot in water one on grass, mountain path and solar crown, divine alchemy',
  'O Diabo':           'horned baphomet on dark stone pedestal, two chained figures below, inverted pentagram torch, shadow materialism chains',
  'A Torre':           'stone tower struck by lightning bolt, crown flying off top, two figures falling into darkness, storm clouds dramatic light',
  'A Estrela':         'serene woman kneeling pouring water under eight-pointed starlit sky, birds in tree, hope renewal cosmic peace',
  'A Lua':             'full moon between two stone towers, wolf and dog howling at moon, crayfish emerging from dark pool, mysterious path into distance',
  'O Sol':             'radiant sun with human face shining, joyful child on white horse, abundant sunflowers, stone wall, pure vitality',
  'O Julgamento':      'archangel with golden trumpet above clouds, figures rising from open coffins below, mountains of ice, cosmic awakening rebirth',
  'O Mundo':           'dancing figure wrapped in purple sash inside victory wreath of leaves, four living creatures at corners, two wands, wholeness completion',
};
